Updated submodule
AquaticInformatics/ONE.Interfaces.CSharp pull request #32
Opened 2023-04-05 13:15 UTC by AQI-DanG

This will allows us to support Data Qualifier Rule 2 [https://aquaticinformatics.atlassian.net/wiki/spaces/XL/pages/44662836/Definition+Data+Qualifier+Rule](url)

2023-04-05 13:21 UTC, KentMiller approved these changes

2023-04-06 14:32 UTC, JonathanRobertson-AQI requested changes
please adjust version prefix to match standard (-1)

2023-04-06 21:29 UTC, AlanLiu-AI approved these changes

2023-04-06 23:15 UTC, tomsmith-ai approved these changes

2023-04-07 14:28 UTC, JonathanRobertson-AQI approved these changes

2023-04-10 19:34 UTC, merged