AF-248 Updated submodule to generate new values of the enum
AquaticInformatics/ONE.Interfaces.CSharp pull request #86
Opened 2024-10-10 22:12 UTC by vova-nazarenko

2024-10-10 22:27 UTC, MartinBenn-AI approved these changes

2024-10-10 22:52 UTC, AQI-DanG requested changes
Please work with other team members to ensure we do not have any version conflicts

2024-10-10 22:52 UTC, AQI-DanG commented on CHANGELOG.md
> +## Version 6.15.0-AF-248 - 2024-10-10
Typically we do not add pre-release versions to the changelog and we definitely should not have pre-release versions with the same version number

2024-10-11 13:36 UTC, AQI-DanG requested changes
I think we might need a quick call on this.  The changes that @josephquiroz  published as pre-release 6.15.0-pre-XX are actually breaking changes and should have been 7.0.0-pre-XX.  I think they are also not ready for publication in a non-pre-release version.  Because the enum changes are minimal my suggestion would be to publish those as the 6.15.0 release package.  We should also remove the current pre-release packages for that version and ensure that Joseph includes your changes in his publication of the 7.0.0 package.

@JonathanRobertson-AQI  and @MartinBenn-AI  - thoughts?

2024-10-11 14:36 UTC, AQI-DanG commented
This should also contain a change to the version in the csproj file

2024-10-11 18:50 UTC, closed without merging